[project]
name = "bookshell"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.9",
    "httpx>=0.28.1",
    "sqlalchemy>=2.0.38",
]
